# Generated by Django 4.2 on 2024-07-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shifttime",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="shifttime",
            name="reserved_capacity",
        ),
    ]
