# Generated by Django 4.2 on 2024-07-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_remove_shifttime_capacity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctoruser",
            old_name="sepecialist",
            new_name="specialist",
        ),
    ]
